spring.datasource.url=postgresql://fsd_user:hyZHO9YX21tiDsAzFdPu9V9FEBstOr6v@dpg-d7nruf8sfn5c73ea3qrg-a/fsd_db_iqcz
spring.datasource.username=fsd_user
spring.datasource.password=${hyZHO9YX21tiDsAzFdPu9V9FEBstOr6v}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}