spring.datasource.url=jdbc:postgresql://dpg-d7nqpr8g4nts73bcsejg-a:5432/fsd_db_dtoh?sslmode=require
spring.datasource.username=fsd_user
spring.datasource.password=s5ZhaKO7M8uo0CDID5Y3Mt4X5UxbOE5S

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true